[package]
name = "twenty-twenty-two"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = ">= 0.4.17"
lazy_static = ">= 1.4.0"
regex = ">= 1.7.0"
substring = ">= 1.4.5"
